language: php

php:
  - '7.1'
  
services:
  - mysql

addons:
  hosts:
    - doubleloop.dev 
    
before_install:
  - mysql -e 'CREATE DATABASE doubleloop_dev;'
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  
install:
  - composer install
    
before_script:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - ./wp-cli.phar core download --allow-root --path=wordpress
  - ./wp-cli.phar core config --allow-root --dbname=doubleloop_dev --dbuser=travis --dbhost=localhost --path=wordpress
  - ./wp-cli.phar core install --allow-root --admin_name=admin --admin_password=admin --admin_email=admin@example.com --url=http://doubleloop.dev --title=WordPress --path=wordpress
  - git clone https://github.com/ngm/doublepress.git wordpress/wp-content/themes/doublepress
  - ./wp-cli.phar theme activate doublepress --path=wordpress

script:
  - phantomjs --webdriver 4444
  - php vendor/codeception/codeception/codecept run acceptance
